### ISSUE TITLE
Enable Proxy for Default ( Quiz )

### ISSUE THREAD

**Issue by sylar-my** [escalate/oh-my-zsh-proxy-plugin#1]
It is really clean and nice plugin. Is it any way to be enable proxy as default. I have to run "proxy" every times when new shell is opening.

**Comment by escalate** [comment]
Hello @sylar-my 
I will try to implement your wish.
However, I cannot currently estimate the implementation in terms of time.
Best regards
Felix

**Comment by escalate** [comment]
Hello @sylar-my

I have found a simple solution to your problem.
I have updated the README for this.

https://github.com/escalate/oh-my-zsh-proxy-plugin#enable--disable-proxy-environment-settings-by-default

Best regards
Felix
